### ISSUE TITLE
Eiffel bundle: Mongo-Seed service is not started when '-s' flag provided

### ISSUE THREAD

**Issue by tobiasake** [eiffel-community/eiffel-easy2use#28] opened 2019-09-25 07:13 UTC
### Description
When Eiffel bundle is started with few components with "-s" flag then "mongo-seed" service is not started/loaded and no subscriptions becomes available in Eiffel-Intelligence.

Fix so Mongo-seed service is launched also when few Eiffel components configured to start.

This issues is seen in Docker.
Check also that this issue don't occur when executed in Kubernetes.

**Comment by pef-ericsson** [comment] 2023-04-14 12:43
@e-backmark-ericsson @m-linner-ericsson 
Perhaps that's not a _bug_. Yet, the valid service name is **"mongo_seed"** instead of **"mongo-seed"**.
I have tested it on **Docker** and **K8S** and the installation was correct as it's shown in the attached photo. 
![mongo_seed service](https://user-images.githubusercontent.com/129857813/232045988-6611f66b-5a4b-4cbd-bd92-c5bab79e389a.png)

**Comment by e-backmark-ericsson** [comment] 2023-04-17 08:02
I think the issue is that if not the full Eiffel bundle but just parts of it (like RabbitMQ, Jenkins, EI and ER for example) are explicitly requested through -s flags, then the mongodb seeding is not done.
So, try to start using e.g. something like './easy2use start Eiffel -s <rabbit> -s <jenkins> -s <ei-frontend> -s <ei-backend-artifacts> -s er' (replace services in <> with real service names)

**Comment by m-linner-ericsson** [comment] 2023-04-26 12:40
@tobiasake Would you expect that `mongo_seed` should be started with the Eiffel Intelligence or was there any other service it should be connected with? Could you provide a example of a working command and one where it doesn't work?

**Comment by m-linner-ericsson** [comment] 2023-05-10 07:47
@tobiasake If I interpret you correct, this ticket is about starting the `mongo_seed` when EI is started.

**Comment by tobiasake** [comment] 2023-05-10 08:41
@m-linner-ericsson Yes, some dependency start of mongo_seed. But sametime maybe there is use-cases where user just want to start Eiffel-Intelligence without subscriptions loaded from mongo_seed. So maybe its better to have it like is today and add some docs about mongo_seed application name need to be specified to -s flag if user want to have the subscription loaded from mongo_seed application/container.

**Comment by m-linner-ericsson** [comment] 2023-06-07 12:08
Closing this as https://github.com/eiffel-community/eiffel-easy2use/pull/84 is merged

**Closed by m-linner-ericsson** 2023-06-07 12:08 UTC
Labels: bug
